/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_com_opengldome_ndk_Gllib */

#ifndef _Included_android_com_opengldome_ndk_Gllib
#define _Included_android_com_opengldome_ndk_Gllib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_com_opengldome_ndk_Gllib
 * Method:    creatBaseProgram
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_com_opengldome_ndk_Gllib_creatBaseProgram
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
